In [1]:
import numpy as np

# Ejercicios de "La libreria numpy y los arrays".

## Ejercicio 1

Crear un array de datos con valores entre 5 y 120.

In [2]:
print(np.arange(5, 121))

[  5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20  21  22
  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40
  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58
  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76
  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94
  95  96  97  98  99 100 101 102 103 104 105 106 107 108 109 110 111 112
 113 114 115 116 117 118 119 120]


## ejercicio 2

Crear una matriz 4x4 con los valores desde 0 hasta 15.

In [4]:
print(np.arange(0, 16).reshape((4, 4)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


## ejercicio 3

Crear la identidad de 7x7.

In [6]:
print(np.eye(7))

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


## ejercicio 4

Crear un array de 20 elementos y transformarlos en una matriz 5x4.

In [11]:
x = np.arange(20)
print(x.reshape((5, 4)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


## ejercicio 5

Crear un array con 20 números con los valores entre 0 y 5 espaciados de forma uniforme.

In [10]:
print(np.linspace(0, 5, 20))

[0.         0.26315789 0.52631579 0.78947368 1.05263158 1.31578947
 1.57894737 1.84210526 2.10526316 2.36842105 2.63157895 2.89473684
 3.15789474 3.42105263 3.68421053 3.94736842 4.21052632 4.47368421
 4.73684211 5.        ]
